HW2 is completed
MoshKillaPit/OtusHomework pull request #1
Opened 2024-08-19 14:27 UTC by MoshKillaPit

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-08-20 06:12 UTC, vladislavmass requested changes

2024-08-20 06:12 UTC, hungry-honeybadger commented on hw02_fix_app/reader/pkg.go
> +func ReadJSON(filePath string, _ int) ([]types.Employee, error) {
Лишний аргумент нужно просто убрать. Что бы сигнатура функции была такой `func ReadJSON(filePath string) ([]types.Employee, error)`

2024-08-20 06:12 UTC, hungry-honeybadger commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Нет никакого смысла продолжать обработку файла, если мы не смогли его открыть. Поэтому нужно вернуть ошибку `return nil,err`

2024-08-20 06:12 UTC, hungry-honeybadger commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Нужно уведомить вызывающий код о том, что при считывание файла произошла ошибка. Поэтому нужно вернуть ошибку `return nil,err`

2024-08-20 06:12 UTC, hungry-honeybadger commented on hw02_fix_app/reader/pkg.go
> +		return nil, nil
Нужно уведомить вызывающий код о том, что при считывание файла произошла ошибка. Поэтому нужно вернуть ошибку `return nil,err`

2024-08-20 12:18 UTC, MoshKillaPit commented on hw02_fix_app/reader/pkg.go
> +		return nil, nil
Убрал строчку 		fmt.Printf("Error: %v", err) . 
Буду очень благодарен если объясните всё понятным языком, просто тяжко это ДЗ даётся

2024-08-20 12:24 UTC, MoshKillaPit commented on hw02_fix_app/reader/pkg.go
> +func ReadJSON(filePath string, _ int) ([]types.Employee, error) {
Исправил

2024-08-20 12:27 UTC, MoshKillaPit commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Исправил

2024-08-20 12:28 UTC, MoshKillaPit commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Исправил

2024-08-22 14:18 UTC, vladislavmass approved these changes

2024-09-12 16:57 UTC, merged