Hw03_chessboard
MoshKillaPit/OtusHomework pull request #2
Opened 2024-08-25 12:53 UTC by MoshKillaPit

2024-08-25 17:05 UTC, vladislavmass requested changes

2024-08-25 17:05 UTC, vladislavmass commented on hw03_chessboard/go.mod
>  module github.com/fixme_my_friend/hw03_chessboard
Неверное имя модуля

2024-08-25 17:05 UTC, vladislavmass commented on hw03_chessboard/main.go
> +	fmt.Scanf("%d", &size)
Было бы неплохо обработать ошибку ввода и прекратить работу если она произошла

2024-08-26 14:03 UTC, vladislavmass approved these changes

2024-08-26 14:03 UTC, vladislavmass commented on hw03_chessboard/main.go
> +	fmt.Scanf("%d", &size)
Как мы видим по [документации](https://pkg.go.dev/fmt#Fscan) функция `fmt.Scanf` возвращает 2 значения , одно из которых имеет тип error. это значит что эта функция может вернуть ошибку и мы можем ее обработать. 
Выглядеть это может примерно вот так
```
_,err:=fmt.Scanf("%d", &size)
if err!=nil{
    fmt.Println(err)
    os.Exit(1)
}
```

2024-09-12 16:51 UTC, SaveliiYam approved these changes

2024-09-12 16:51 UTC, SaveliiYam commented on hw02_fix_app/go.mod
> -module github.com/fixme_my_friend/hw02_fix_app
+

2024-09-12 17:01 UTC, merged